// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psdigmobuhwuntvqdire.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZGlnbW9idWh3dW50dnFkaXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzMzMTAsImV4cCI6MjA2NDk0OTMxMH0.gNgaa1CbnCb1arRSBFlaFNkIosh_kMiTGwiE0Vbq8ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);